version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy -v

changelog:
  use: github
  sort: asc
  groups:
    - title: Maintenance
      regexp: '^chore.*'
      order: 100
    - title: Stories
      regexp: '^story.*'
      order: 200

builds:
  - id: echo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    main: example/custom_framework/echo/main.go
    binary: echo

  - id: simple_queue
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    main: example/simple_queue/main.go
    binary: simple_queue

dockers:
  - id: echo
    goos: linux
    goarch: amd64
    goamd64: v3
    ids:
      - echo
    image_templates:
      - "ghcr.io/z5labs/bedrock/example/custom_framework/echo:latest"
      - "ghcr.io/z5labs/bedrock/example/custom_framework/echo:{{ .Tag }}"
    dockerfile: example/custom_framework/echo/Containerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

  - id: simple_queue
    goos: linux
    goarch: amd64
    goamd64: v3
    ids:
      - simple_queue
    image_templates:
      - "ghcr.io/z5labs/bedrock/example/simple_queue:latest"
      - "ghcr.io/z5labs/bedrock/example/simple_queue:{{ .Tag }}"
    dockerfile: example/simple_queue/Containerfile
    use: docker
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
