name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: Lint Go Code
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
            skip-cache: false
            skip-pkg-cache: false
            skip-build-cache: false
            args: --timeout 3m --verbose --print-issued-lines=true --skip-dirs example --skip-files ".*_test.go"

        - name: Build
          run: go build ./...

        - name: Test
          run: go test -race -cover ./...