name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - "main"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

        - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
          with:
            go-version: '1.22'

        - name: Lint Go Code
          uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
          with:
            version: latest
            skip-cache: false
            args: --timeout 3m --verbose --print-issued-lines=true --skip-dirs example --skip-files ".*_test.go"

        - name: Build
          run: go build ./...

        - name: Test
          run: go test -race -cover ./...

        - name: Build example container images
          uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6
          with:
            distribution: goreleaser
            version: latest
            args: release --clean --snapshot
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
