name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}

        - uses: actions/setup-go@v5
          with:
            go-version: '1.21'

        - name: Lint Go Code
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
            skip-cache: false
            skip-pkg-cache: false
            skip-build-cache: false
            args: --timeout 3m --verbose --print-issued-lines=true --skip-dirs example --skip-files ".*_test.go"

        - name: Build
          run: go build ./...

        - name: Test
          run: |
            go test -race -coverprofile=coverage.out ./...
            go tool cover -func=coverage.out -o=coverage.out

        - name: Go Coverage Badge
          uses: tj-actions/coverage-badge-go@v2
          with:
            filename: coverage.out
            text: coverage
            green: 90

        - uses: stefanzweifel/git-auto-commit-action@v5
          id: auto-commit-action
          with:
            commit_message: 'chore(docs): update coverage badge'
            skip_fetch: true
            skip_checkout: true
            file_pattern: ./README.md

        - name: Push Changes
          if: steps.auto-commit-action.outputs.changes_detected == 'true'
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ github.token }}
            branch: ${{ github.ref }}

        - name: Build example container images
          uses: goreleaser/goreleaser-action@v5
          with:
            distribution: goreleaser
            version: latest
            args: release --clean --snapshot
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
