name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

        - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
          with:
            go-version: '1.23'

        - name: Lint Go Code
          uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
          with:
            version: latest
            skip-cache: false
            args: --timeout 3m --verbose --print-issued-lines=true --skip-dirs example --skip-files ".*_test.go"

        - name: Build
          run: go build ./...

        - name: Test
          run: go test -race -cover ./...
